### ISSUE TITLE
KSS playing issue

### ISSUE THREAD

**Issue by andiandi13** [vitamin-caig/zxtune#1195]
Hi,

I have a big issue reading KSS files, rather from MSX or Game Gear

First of all, that issue applies to all types of archives :

- With a .kss with one .m3u
- With a .kss with multiple .m3u
- With a .kss only

Two cases :

- The main problem is that ZXTunes only read _one_ song of the KSS file the moment I touch the archive, or the .kss file extracted from the archive. The song plays for ever... I can't seek, I can't change tracks...

- Also, sometimes, ZXTunes read a silent song for ever.

I guess that the normal behavior of ZXTunes would be to enter inside the archive and display all the tracks to let me choose the one I wanna play, as it does with .nsf and .gbs files.

I tested it on many devices, on many firmwares (Gingerbread, Kit Kat, Nougat, Oreo...), and it's the same.

**Comment by vitamin-caig** [comment]
This bugtracker is robot-only!

So, please duplicate your issue at https://bitbucket.org/zxtune/zxtune/ and specify problematic kss file.

JFYI:
- there's only one track in .kss file, only .kssx files has multiple tracks
- .m3u files are not supported

**Comment by andiandi13** [comment]
> This bugtracker is robot-only!

Sorry I didn't know at all

I'm going to bitbucket then
