### ISSUE TITLE
Rpm package problem

### ISSUE THREAD

**Issue by TeknoMobil** [vitamin-caig/zxtune#1292]
Hi
New version Rpm package cannot be installed on Fedora.

https://zxtune.bitbucket.io  b4500 RedHat x86_64

**Comment by vitamin-caig** [comment]
Hello!

This bugtracker is robot-only (it's noticed in repo header), so please make an issue at https://bitbucket.org/zxtune/zxtune/issues?status=new&status=open
Also specify:
- OS version you are using (also uname -a and /etc/issue content)
- installation error in details
