### ISSUE TITLE
(Android) Crackling sound during playback of GBA gsf files

### ISSUE THREAD

**Issue by coderkei** [vitamin-caig/zxtune#2185]
On the latest release version for Android (b4971 thin), during playback of Gameboy Advance GSF files, a noticeable crackling sound can be heard. It seems to happen for all the GSF files I tested for various games. This did not occur before the latest update where the fade options were added. I currently have fade in and out disabled.

I have tested various GSF files for games including Pokemon Sapphire, Yu Gi Oh GX Duel Academy and Sonic Advance 1, 2, 3 and the music for all them has a weird crackling sound that I didn't hear on the previous version.

Device is an Oppo Reno running Android 10. Build info in the app says arm64-v8a normal long port.

**Comment by coderkei** [comment]
I have tried the latest r4980-thin version and unfortunately the same issue still occurs. Any ideas on a cause?

**Comment by vitamin-caig** [comment]
Do you have another devices to check out?

**Comment by coderkei** [comment]
I tried on my Xiaomi Redmi 9A too, running Android 10 and it has the same issue on build 4980.

I played Littleroot town from Pokemon sapphire as that seems to show the issue well. The crackling resembles vinyl record crackling you could say.

I was trying some older APKs on both devices too and it seems on build 4960, the issue does not occur on either device.

**Comment by vitamin-caig** [comment]
Looks like I've found an issue. I may share fixed desktop version. Can you check it out?

**Comment by coderkei** [comment]
Sure, is it for Windows?

**Comment by vitamin-caig** [comment]
You may compare it with one from public build.
[zxtune123.zip](https://github.com/vitamin-caig/zxtune/files/6009557/zxtune123.zip)

**Comment by coderkei** [comment]
Okay, I tried the build you sent me and then compared with the latest public version from https://zxtune.bitbucket.io/.

The latest public version has the crackling, while the build you linked above seems to have that issue fixed and no longer crackles.

**Comment by vitamin-caig** [comment]
Excellent! So fix will be available in the nearest release.

**Comment by coderkei** [comment]
Thank you!
