### ISSUE TITLE
Update libvgm for next version? updates fixes the file name codepage issue. Now it can finally open and play "スペースハリアー - 03 - Main BGM.vgm". It also fixes the volume balance of the C140 and C219 chips, which was off in v0.50.0. I merged RF5C68 and RF5C164, as they are basically the same chip, so the RF5C164 is now controlled with the RF5C68 settings. 

### ISSUE THREAD

**Issue by juanreina921** [vitamin-caig/zxtune#2187]
Is it possyble you could update libvgm to laytest version for next update of zxtune? Here are changes. YM2612 users: Nuked OPN2 now defaults to unfiltered. You can do per-channel panning to the AY8910 and OPNx SSG. You can enable S98 and DRO playback by editing the .ini file. Thanks so much for zxtune and its updates you rock man!

**Comment by juanreina921** [comment]
Forgot some. updates fixes the file name codepage issue. Now it can finally open and play "スペースハリアー - 03 - Main BGM.vgm". It also fixes the volume balance of the C140 and C219 chips, which was off in v0.50.0. I merged RF5C68 and RF5C164, as they are basically the same chip, so the RF5C164 is now controlled with the RF5C68 settings.

**Comment by vitamin-caig** [comment]
libvgm has been already updated in 'develop' branch.
You have problems with opening files with Japanese symbols in zxtune apps?

**Comment by juanreina921** [comment]
No, I dont think so, but I can look and see if vgm opens with zxtune.

**Comment by juanreina921** [comment]
I looked and it worked. I will now close this issue
