### ISSUE TITLE
Feature request. Add ay emulator to zxtune?

### ISSUE THREAD

**Issue by juanreina921** [vitamin-caig/zxtune#2189]
Hello! I have a feature request. Could it be a possibility for you to add the ay emulator to zxtune ? For those who don't know, ay emul/ay emulator, is a soundchip player, it can accurately play almost all forms of specxy music, including. ST1 - Sound Tracker v1.xx uncompiled; STC, ZXS - Sound Tracker v1.xx, Super Sonic v1.xx; PSC - Pro Sound Creator v1.xx; AS0, ASC - ASC Sound Master v0.xx-2.xx; PT1, PT2, PT3 - Pro Tracker v1.xx-3.xx, Vortex Tracker II v1.0; STP - Sound Tracker Pro; FTC - Fast Tracker v1.xx; FLS - Flash Tracker; SQT - SQ-Tracker; GTR - Global Tracker v1.x; FXM - Fuxoft AY Language; AY of AMAD subtype - Amadeus modules, FXM analog; PSM - Pro Sound Maker. It can also play ZX Spectrum's, Atari ST/STe's or Amstrad CPC's memory dumps with player for processor (Z80 or MC68000) like: AY of EMUL subtype (DeliAY and AYPlay projects files); AYM (RDOSPLAY project files); SNDH (Atari ST or Atari STe music files). In adission, its ym playback far outshines the likes of the player we have rite now, as it plays this song perfectly! []()ftp://modland.com/pub/modules/YM/Tao/dancer.ym other songs from Tao and others use this querk in the soundchip that the player we have rite now , doesn't emulate. I hope this gets added soon, as I would love to listen to these and much more files playing correctly in zxtune. Source code of laytest and stabil. 
[]()https://bulba.untergrund.net/Ay_Emul29b27.src.7z
Thanks again in advance, and keep up the good work with this grate app!

**Comment by vitamin-caig** [comment]
Ehm... Why haven't you checked list of supported by ZXTune formats?

**Comment by juanreina921** [comment]
@vitamin-caig, I did, maybe it's using an older version of ay_emul, because surtain querks aren't being emulated, or ay_emul doesn't have all the cores up to date. Try playing the song above with Windows or Linux ver of ay emul, and then zxtune. []()https://bulba.untergrund.net/Ay_Emul29b27-32.7z
[]()https://bulba.untergrund.net/Ay_Emul29b27-64.7z
[]()https://bulba.untergrund.net/Ay_Emul29b27-32.tar.gz[]()https://bulba.untergrund.net/Ay_Emul29b27-64.tar.gz

**Comment by vitamin-caig** [comment]
ZXTune just doesn't support extended effects while playing YM files.
