### ISSUE TITLE
Add Dynamic Studio Professional module support

### ISSUE THREAD

**Issue by Sembiance** [vitamin-caig/zxtune#2190]
It would be AWESOME if zxtune could add support for "Dynamic Studio Professional" modules.

What little information is known about the format (along with sample files) is here: http://fileformats.archiveteam.org/wiki/Dynamic_Studio_Professional_module

**Comment by vitamin-caig** [comment]
There's WAY too little information available:)

**Comment by Sembiance** [comment]
Yah, you are right. Haven't been able to locate ANY player for this format, not even the original tracker. If I ever come across additional information (especially if I can find a file format odc), I'll add it to the wiki and update this issue with the info. That might be a while though :)

**Comment by vitamin-caig** [comment]
For future - all the pc/amiga/etc formats are supported by openmpt and xmp libraries. So, new format support should be redirected to that libraries maintainers.

**Comment by Sembiance** [comment]
Ahh, whoops, sorry about that. Thanks for the info!
