### ISSUE TITLE
zxtune for Apple Silicon or Universal App

### ISSUE THREAD

**Issue by baxysquare** [vitamin-caig/zxtune#2197]
How difficult would it be to compile either a macOS Universal app or a version exclusively for Apple Silicon?  I know some apps are easily recompiled, but others have x86_64 dependencies that make it difficult or impossible to accomplish.

**Comment by vitamin-caig** [comment]
Implemented unnotarized M1 build in e9c02784452fe106c56a8d1cb55ba1ea76f87665
