### ISSUE TITLE
zxtune123 config files do not work

### ISSUE THREAD

**Issue by Yuril125** [vitamin-caig/zxtune#2198]
Version: Windows

In zxtune123_en.txt, it is specified that a configuration file can be used to specify options for the program. However, the program does not appear to apply the options in the configuration file.

To reproduce:
Create a file "onlyA.conf" in the working directory with the following content:

zxtune.core.aym.clockrate=2000000
zxtune.sound.loopmode=1
zxtune.sound.mixer.3.0_0=100
zxtune.sound.mixer.3.0_1=100
zxtune.sound.mixer.3.1_0=0
zxtune.sound.mixer.3.1_1=0
zxtune.sound.mixer.3.2_0=0
zxtune.sound.mixer.3.2_1=0

Then, run `zxtune123.exe --config onlyA.conf "..\DNK - PopsDemo1.stp"`. 
Only Channel A should play, since the volume levels for Channel A are set to 100% while the volume levels for Channels B and C are set to 0. However, when this command is run, all of the channels play nevertheless.

The program appears to be able to read the file, as when the file name in the command is changed to a nonexistent file, the program throws an error and quits. However, when the file name is typed as `onlyA.conf`, the program runs as normal, but does not apply the options in `onlyA.conf`.

**Comment by vitamin-caig** [comment]
Fixed in c827a88b1
