### ISSUE TITLE
Conversion doesn't work in >5000 builds

### ISSUE THREAD

**Issue by kolnogorov** [vitamin-caig/zxtune#2200]
If you try to convert something, you'll get an "Conversion mode is not specified" error, even though the "mode" parameter is specified.

For example:

```
zxtune123 --convert mode=psg,filename=music.psg music.pt3
```

Will always throw:
```
Conversion mode is not specified.
```

In 4990 build (and eariler) everything is ok.

Tested on Ubuntu 20.04, macOS 12.5.1 and Windows 11.

**Comment by vitamin-caig** [comment]
Fixed in 3fb63f9
