### ISSUE TITLE
zxtune-android: support gesture navigations in Android 12

### ISSUE THREAD

**Issue by ghost** [vitamin-caig/zxtune#2204]
Hi

If you go to preferences, there is no way to go back to the playlist (or I can't find it)

**Comment by vitamin-caig** [comment]
Just press back

**Comment by 486DX2** [comment]
There is no back arrow in zxtune itself and on my android 12 tablet at the bottom also no back button appears.
So whenever I go into preferences of zxtune, I need to kill the program because I can't go back :(

**Comment by vitamin-caig** [comment]
There're always should be available 3 hardware or on-screen buttons: home, last tasks and back. How do you kill the program?

**Comment by 486DX2** [comment]
They are not present on my tablet! It's android 12. They were on my previous tablet, on android 7.

I can move the program up with my finger and then it becomes smaller on the background of android.
After that you can move this smaller window on the background up to the top of the screen which stops the program.
So every time i go into preferences I need to do this :(

**Comment by vitamin-caig** [comment]
Quick googling gives me this:

If you don’t like Google’s new gesture-based navigation, you don’t have to struggle with it. There’s a really simple method for bringing back the back button in Android. Just follow these steps:

Go To Settings > System
Inside System, Locate The 3 Button Navigation Switch To Turn on Android’s Standard Navigation Buttons
Once Selected, Your Phone Will Revert Back To The Standard Android Configuration With A Trio of Buttons From Left to Right That Include: Back (Triangle), Home (Circle), and Square Icons (App Drawer)
And If You Want To Go Back To Google’s New Gesture System, Simply Open Settings > System > Gestures > System Navigation > Toggle “Gesture Navigation” On

**Comment by 486DX2** [comment]
YES!!!!
I didn't know this so I have enabled the 3 bittons again. I can now go back from preferences!
