### ISSUE TITLE
zxtune-android: add library name

### ISSUE THREAD

**Issue by 486DX2** [vitamin-caig/zxtune#2205]
Hi

I would love to see which library is currently used for playing a file. So I mean one of the sound libraries zxtune is using.
Is that easy to add?

You could add it below 'program' at the left.

**Comment by vitamin-caig** [comment]
What if several libraries are used?

**Comment by 486DX2** [comment]
I don't understand how a file can be played by 2 libraries at the same time.
According to me, this is impossible

Can you give an example?

**Comment by vitamin-caig** [comment]
E.g. in order to play .mp3 used internal parsing and external decoding. Both parts are essential.

**Comment by 486DX2** [comment]
Ok I understand.
Do you want to add this small 'information' feature?
I would really like to see this information zince my chiptunes are so many different formats.

Thanks
Lisa

**Comment by vitamin-caig** [comment]
What library name information is for?

**Comment by 486DX2** [comment]
It's interesting to see when you are playing a file.
You could display somerhing like this: 
NES Sound Format (NSF)
Game Emu

First the format and then below what library is playing it.

**Comment by vitamin-caig** [comment]
It's quite specific information. For some formats there's 'platform' trait available. Hope, sometime this will be used to display additional information (e.g. picture with console)

**Comment by 486DX2** [comment]
So you mean you don't like it?

**Comment by vitamin-caig** [comment]
Yep. Moreover, it's error-prone a bit.

**Comment by 486DX2** [comment]
Also the format type you can't display?
Is there no code that tells the file format without any error possible?
How else to know what library must be used to play that file?
