### ISSUE TITLE
request: library for other programs

### ISSUE THREAD

**Issue by 486DX2** [vitamin-caig/zxtune#2206]
Hi

I requested zxtune support in Mixxx here: https://github.com/mixxxdj/mixxx/issues/11119

I'm not a developer so I ask your help to explain how they can do this.
Is there a library of zxtune that just can be used very easy in another project?

Please reply there for help how this can be done.
I don't have the knowledge :(

thx

**Comment by vitamin-caig** [comment]
There is an outdated libzxtune originally created for integration to another project. But it's outdated now and not suitable for integration.

**Comment by 486DX2** [comment]
Do you want to update it?
It would be perfect for integration in the Mixxx project (see other issue).

**Comment by 486DX2** [comment]
And you can share it across all players for all platforms.

**Comment by vitamin-caig** [comment]
No plans to update.
zxtune integration should be made in target app's infrastructure using C++ interfaces.
