### ISSUE TITLE
zxtune-android: playlist sort by program

### ISSUE THREAD

**Issue by 486DX2** [vitamin-caig/zxtune#2207]
Hi

Since I add different zipped files to my playlist and each zip file is a collection of all songs of a game, I would like to sort the playlist by 'program'. In this way they are grouped by program name and I can play game by game song collections.
This is currently not possible I think.

Are you interested to add this sorting?

For this to'be usefull, there should also be added an option to display either the author or program in the playlist (which now always displays the author). This choice could be put in preferences window.

Thanks
Lisa

**Comment by vitamin-caig** [comment]
It's not a good idea to overload playlist items with such a redundant information. And you can't sort items by something that is not visible.

Moreover, I've tried to implement that column in desktop version - it was not as good as expected, not all the tracks contain this information.

**Comment by 486DX2** [comment]
So 'program' is information the author of the track puts inside but many tracks don't have it?
Ok, if this is correct,then it's not a good idea.

**Comment by vitamin-caig** [comment]
It depends. Sometime it's program track was created in. Sometime it's a game track was ripped from. Sometime it's a software used to rip track.
