### ISSUE TITLE
zxtune-android: request equalizer

### ISSUE THREAD

**Issue by 486DX2** [vitamin-caig/zxtune#2209]
Hi

For me personally, I would love an equalizer in android version.
I like to crank up the bass and treble :p
Maybe interested in this?
Could be put in separate window you can open (like preferences) and close so it's not on the screen when playing.

**Comment by 486DX2** [comment]
And if interested, you can make EQ presets you can save/load or just some default presets like most players have.

**Comment by vitamin-caig** [comment]
App supports external equalizers for now. E.g. 'Poweramp equalizer'.
