### ISSUE TITLE
ZX Tune randomly crashing while playing music

### ISSUE THREAD

**Issue by Domarius** [vitamin-caig/zxtune#2211]
I've used ZX Tune for years without an issue, this may be related to an update of some dependant files.  

There doesn't seem to be a rhyme or reason, I will be playing various chiptunes (SNES, NES, etc.) and suddenly ZX Tune will close, sometimes mid-song, sometimes just before playing the next song.  If I re-open it and find the song it was playing, it will continue playing the song and move onto the next, just fine.

ZX Tune version: `zxtune-qt r5020 Sep 28 2022 linux-x86_64`

This is the error it gives in the terminal when I run it with the terminal open:
```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

std::exception
```

This is my operating system:
```
Operating System: EndeavourOS
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.2-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700K CPU @ 4.00GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
```

**Comment by vitamin-caig** [comment]
Should be fixed in e72820f991386294a35914a73decbd713213d2ef
