### ISSUE TITLE
why does .MOD .XM .IT sound so good? 

### ISSUE THREAD

**Issue by coderofsalvation** [vitamin-caig/zxtune#2214]
Thank you for zxtune :)
What engine is being used to play back these formats?

**Comment by vitamin-caig** [comment]
You're welcome:)

[libopenmpt](https://lib.openmpt.org/libopenmpt/) is used for the most of tracker formats, for the rest ones [libxmp](https://github.com/libxmp/libxmp) is used.

**Comment by coderofsalvation** [comment]
awesome thx for answering!
