### ISSUE TITLE
POLL: composer's workflow (clouddrive?)

### ISSUE THREAD

**Issue by coderofsalvation** [vitamin-caig/zxtune#2215]
As a composer, I love the portability of trackermodules.
They just never break, and contain 0 external fxplugin-dependencies like modern DAW-formats.

So my current workflow is: I use clouddrives (gdrive/ssh) on my laptop/desktop to save my work-in-progress modules to.
Preferabbly I listen to them in ZXTune, but since only VLC (android) supports browsing ssh-folders, I use VLC for previewing while I'm in the gym etc.
(I guess many artists listen/tweak modules several times on various devices, before releasing it to modarchive etc).

Ideally, I'd love to do all discovery AND work-in-progress-previewing in ZXtune.
Any suggestions for a workflow which does not force me to manually download modules?

If ZXtune would support mounting custom libraries using urls...what format would you prefer?

◻ ssh
◻ git-repo
◻ http opendirectory (like modland.com)
◻ not needed, just download (or mount) the mod(folder) you want to preview (*)

* = anyone used ZXTune with some kind of SSH mount-android-app?

kind regards

**Comment by vitamin-caig** [comment]
Since it's extremely specific feature (but requires significant amount of efforts), just use generic solution with mounted remote folder visible as local one.

**Comment by coderofsalvation** [comment]
thanks!
