### ISSUE TITLE
Some models cannot be played

### ISSUE THREAD

**Issue by gitatw** [vitamin-caig/zxtune#2217]
I get an error when I open a song:
"java.lang.UnsatisfiedLinkError: dlopen failed: library libzxtune.so not found"
Regardless of the format, nothing can be played.

It can be played without problems on other models.
It feels like a unique problem of Unihertz jelly2.
Sometimes the app icon of the apk file did not appear correctly, and although I could still install it, it sometimes suddenly quit during operation.

Operation check:
ZXTune r4990, r5000, r5030
Unihertz jelly2
Android11
internal storage ONLY

**Comment by vitamin-caig** [comment]
Could you please open 'About' panel from main menu, scroll down to see some technical info and attach a screenshot here?

**Comment by gitatw** [comment]
![zxtune_about](https://github.com/vitamin-caig/zxtune/assets/29173143/eb4f8272-64bf-4ae7-bd58-44e6841fff98)

screenshot
How about this?

**Comment by vitamin-caig** [comment]
Looks like GooglePlay has provided you corrupted version. I see you are using Japanese locale while app is still in english.
Try to install apk from site: https://zxtune.ru

**Comment by gitatw** [comment]
After installing the .apk from the site above, it is now displayed in the correct language and can be played
Thank you very much
