### ISSUE TITLE
Wrong VGM CRASH/not found

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [vitamin-caig/zxtune#2218]
[VGM_FAIL.zip](https://github.com/vitamin-caig/zxtune/files/11751689/VGM_FAIL.zip)

это с эксперементальной конвертилки из WAV в Ay
когда отлаживал сохранение оно успешно утя\умя не фурычило
не обращай внимание на унылое кашоство (хотя лучшого достигнуто и не было...)

![2023-06-15_040257](https://github.com/vitamin-caig/zxtune/assets/88002487/ca5873bc-cc10-4116-b012-f0cad98571de)
(деление на 0)

vgm input plugin v0.50.1
by Valley Bell 2020
для winamp-а их спокойно переваривает
правда без бегунка времени

**Comment by NEO-SPECTRUMAN** [comment]
![2023-06-15_042701](https://github.com/vitamin-caig/zxtune/assets/88002487/96fdb481-377a-462d-ad87-2ea36f1d0122)
тута?

**Comment by NEO-SPECTRUMAN** [comment]
самое первое чтение тут
![2023-06-15_042829](https://github.com/vitamin-caig/zxtune/assets/88002487/9d1b6ae2-e55d-4e59-830f-49f05160cab0)

**Comment by NEO-SPECTRUMAN** [comment]
это не на твоей стороне?
GetCurTime
GetTotalTime
итд все вызывающие Tick2Second

**Comment by vitamin-caig** [comment]
Исправлено в c73d23017d59b82a . Будет использоваться длительность по умолчанию для таких случаев.
