### ISSUE TITLE
Zxtune android weird volume increase

### ISSUE THREAD

**Issue by bitten2up** [vitamin-caig/zxtune#2219]
at the end of playing a file it seems to have an audible increase in the volume, i have fade in and fade out enabled and are playing gfslib files (gba)

https://github.com/vitamin-caig/zxtune/assets/55027142/21f91869-b710-42c0-82bf-0cbdab808e7b

experienced on SM-A426U
version r5030-thin instead from the playstore

**Comment by vitamin-caig** [comment]
Please attach also problematic tracks with dependent file

**Comment by vitamin-caig** [comment]
Please check out if fixed version has an issue
[zxtune_r5030-142-gf59ec0da2_arm64-v8a.apk.zip](https://github.com/vitamin-caig/zxtune/files/11788743/zxtune_r5030-142-gf59ec0da2_arm64-v8a.apk.zip)

**Comment by vitamin-caig** [comment]
Fixed in 7e2d561811d70816. Closed since no reply.

**Comment by bitten2up** [comment]
ah sorry didn't get the notification for that 2 weeks ago testing now

**Comment by bitten2up** [comment]
sounds good thx
