### ISSUE TITLE
new media libraries to be added

### ISSUE THREAD

**Issue by thebelovedmoon** [vitamin-caig/zxtune#2220]
with the release of the PS5 (PlayStation 5) joshw has added a new repository to their list of databases, the newest being the **PS5** repository shown here:

- psf5.joshw.info [(see url)](https://psf5.joshw.info)

might update this issue if I can find more libraries^^~

**Comment by vitamin-caig** [comment]
I'm in doubt. There' only 3 archives in that catalogue and only 278 supported tracks found among them.

P.S. I have full joshw catalogue copy, all 4.3T of data:)

**Comment by vitamin-caig** [comment]
Added in 4b8256947374439c87db785fde78ede3ef0f3732

**Comment by thebelovedmoon** [comment]
ooh I see!! can't wait for the new list in-app^^~

**Comment by vitamin-caig** [comment]
> 

It's already in the most recent version (5040).
