### ISSUE TITLE
Bug: ZXTune is starting along with the bluetooth

### ISSUE THREAD

**Issue by vsub** [vitamin-caig/zxtune#2221]
I don't know if it's a bug or a feature but every time I turn on my bluetooth to send some files to my laptop,the player appear in the pull down menu
There is nothing about bluetooth permissions so why is it starting

**Comment by vitamin-caig** [comment]
Looks like it's not connected with bluetooth itself, but with media devices using it. I'll take a look.

**Comment by vitamin-caig** [comment]
Fixed in 155297de0de7fb446496e8206d
