### ISSUE TITLE
Permissions seemingly broken on Android 14

### ISSUE THREAD

**Issue by SageSystems** [vitamin-caig/zxtune#2226]
On android 14 the storage access API is seemingly broken, however this may be a grapheneos specific issue and I'd like other people to chime in on this. Looking for people running android 14 (mostly pixel users) to confirm this.

**Comment by ingelsse** [comment]
I have the same problem. I try to give zx permission to use a folder but it keeps asking me to give zx permission over and over again. zx does not have permission to change any system setting (not sure if this could be a thing at all)

**Comment by vitamin-caig** [comment]
Fixed in 2d34613

I was very upset due to such a rough backward compatibility breakdown from Google.
