### ISSUE TITLE
VGM support to Mixxx

### ISSUE THREAD

**Issue by ghost** [vitamin-caig/zxtune#2227]
HI

Are you interested in adding VGM support to Mixxx?

https://github.com/mixxxdj/mixxx/issues/12122

**Comment by vitamin-caig** [comment]
It depends. I can give consultations about integrating zxtune to mixxx, maybe made some reasonable changes in code, but main work should be implemented on the acceptor's side.

**Comment by vgm-girl** [comment]
Hi

I'm an autistic girl and it's impossible for me to learn programming to do this myself. I have disabilities because of my autism.
It's my DREAM to have VGM in Mixxx.
Is there a way you want to try this?
You will make my dream come true...

**Comment by vitamin-caig** [comment]
Unfortunately, I have no enough resources to work on foreign and unknown for me projects.

**Comment by vgm-girl** [comment]
FUCK YOU FAGGOT

**Comment by vitamin-caig** [comment]
Closed due to inadequate user

**Comment by vgm-girl** [comment]
> Unfortunately, I have no enough resources to work on foreign and unknown for me projects.

Sorry, I understand!
