### ISSUE TITLE
add to playlist not working

### ISSUE THREAD

**Issue by vgm-girl** [vitamin-caig/zxtune#2228]
Hi

Clicking "add" button for adding music to playlist doesn't do anything here. 

See screenzhot for the system I have

![Screenshot_2023-10-20-04-03-26-784](https://github.com/vitamin-caig/zxtune/assets/148479571/16d3da73-e3c6-4321-8e93-dcaa403858f5)

**Comment by vitamin-caig** [comment]
That buttons adds currently played track. Do you have that?

**Comment by vgm-girl** [comment]
Please look at screenshot (top, right): none of those button allow me to add files to play. So how do I open a file using zxtune?
I searched for a long time and still not found it.

**Comment by vitamin-caig** [comment]
You have to use browser. There you can listen tracks and/or add them to playlist - via mentioned button (for currently played tracks) or all the tracks in selected files and folders.

**Comment by vitamin-caig** [comment]
Scroll the main interface horizontally.

**Comment by vgm-girl** [comment]
THIS PROGRAM IS FUCK SHIT
YOU CANT PLAY ANYTHING

**Comment by vgm-girl** [comment]
Sorry, I had a bad day!
It's working now

**Comment by vitamin-caig** [comment]
What was the problem? Screenshot is quite strange - no pager at the top of the right panel to switch between playlist and browser. Cannot reproduce.

**Comment by vgm-girl** [comment]
I need to scroll horizontally to see at the right the browser. And then back to return to the screen you see here. Yes it's strange :(
But in that way it works. See screenshot for what system I have (it's a tablet)

**Comment by vitamin-caig** [comment]
Is' ok to need to scroll horizontally, I mean that I cannot see tabs at your screenshot. There the example how tablet layout looks on my environment:
![image](https://github.com/vitamin-caig/zxtune/assets/930461/9fa85ccb-49ef-4afc-affa-7862fe6a4a3f)

As you can see, there's two tabs above playlists' toolbar with icon.

**Comment by vitamin-caig** [comment]
@vgm-girl Could you please check up this version - if tabs heading is visible or not?
https://disk.yandex.ru/d/KD1RcIQaPLZ2Kw

**Comment by vgm-girl** [comment]
> @vgm-girl Could you please check up this version - if tabs heading is visible or not? https://disk.yandex.ru/d/KD1RcIQaPLZ2Kw

It works!!!
Can you please put this on google play?

**Comment by ultimatedoomgamer** [comment]
What was changed to make the tabs visible?

**Comment by vitamin-caig** [comment]
> What was changed to make the tabs visible?

The only search result was related to ancient Jetpack library bug: https://issuetracker.google.com/issues/37105263
Fortunately, this helped:)
