### ISSUE TITLE
Feature Request: addition of .lha support

### ISSUE THREAD

**Issue by pr0t0gam3r** [vitamin-caig/zxtune#2229]
This file format is a way to listen to music ripped straight from Amiga games. I will provide sample files if needed, as these files are only in like, one place, lol.

**Comment by vitamin-caig** [comment]
Have you tried your samples in ZXTune?

**Comment by pr0t0gam3r** [comment]
Yes, they didn't work, I tried the rip for Ghouls N' Ghosts and it didnt play.

**Comment by vitamin-caig** [comment]
Please share the archive.

**Comment by pr0t0gam3r** [comment]
https://www.exotica.org.uk/wiki/Main_Page this has all of the lha files. You can search for rips like Ghouls N' Ghosts (Amiga), and Cannon Fodder (Amiga).

**Comment by vitamin-caig** [comment]
> https://www.exotica.org.uk/wiki/Main_Page this has all of the lha files. You can search for rips like Ghouls N' Ghosts (Amiga), and Cannon Fodder (Amiga).
> 
> The only player that I know of that plays these files is gUiADE

There're many Ghouls N' Ghosts matches in search.
UADE formats are not supported. And lha format is supported since 2012.
