### ISSUE TITLE
Problems on Raspberry Pi 4 running latest desktop (Debian Bookworm) AARCH64

### ISSUE THREAD

**Issue by khatharr** [vitamin-caig/zxtune#2230]
Hello. I've upgraded my ancient Pi3 to a Pi4 and installed the latest OS image. I tried installing zxtune from the binary provided on the main page, but it just complained about an unknown file missing. Someone pointed out to me that I was on aarch64 and should try that build instead. I tried it and zxtune123 works, but zxtune-qt fails with:
```
qt.qpa.plugin: Could not find the Qt platform plugin "eglfs" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted
```
I don't know anything about QT, but it looks like it's complaining about a missing dependency. How would I go about installing eglfs? I searched around the web for a while but I wasn't able to find any information about how to get it, only descriptions of what it does.

**Comment by vitamin-caig** [comment]
Hello!

What the desktop environment you are using?

**Comment by khatharr** [comment]
I think it's "Wayfire Wayland", based on the release notes for the OS image. I'm not sure how to get that information from the software itself. I tried clicking around looking for "about", but I only found it on the taskbar, and that was just information about the taskbar itself (LXPanel).

**Comment by vitamin-caig** [comment]
Could you please share an output of:

`QT_DEBUG_PLUGINS=1 ./zxtune-qt`

command in unpacked build directory?

**Comment by khatharr** [comment]
```
QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QP
A.QPlatformIntegrationFactoryInterface.5.3" since plugins are d
isabled in static builds
qt.qpa.plugin: Could not find the Qt platform plugin "eglfs" in
 ""
This application failed to start because no Qt platform plugin
could be initialized. Reinstalling the application may fix this
 problem.

Available platform plugins are: xcb.

Aborted
```

**Comment by vitamin-caig** [comment]
And what about

> And also check if `./zxtune-qt --platform xcb` command works.

?

**Comment by khatharr** [comment]
Same as the original error.

**Comment by vitamin-caig** [comment]
Could you please check out [this build](https://storage.zxtune.ru/builds/dev/zxtune_r5054-5-gf6f4e0bd8_linux_arm64.tar.gz) ?

**Comment by khatharr** [comment]
The GUI launches, but there are some errors in the console:

```
qt.qpa.xcb: XKeyboard extension not present on the X server
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
```

**Comment by vitamin-caig** [comment]
Much better. Does update check work? (Help -> Check updates)

**Comment by khatharr** [comment]
`SSL handshake failed`

Details:
```
SSL handshake failed
@4291099133
--------
```

**Comment by vitamin-caig** [comment]
Please try updated build - the same links as above. Interested in update check again.

**Comment by vitamin-caig** [comment]
It works, I see:)

**Comment by khatharr** [comment]
Hello, lol
o/

**Comment by vitamin-caig** [comment]
Build 5055 for generic linux (x86_64/aarch64/armhf) is on the air.
