### ISSUE TITLE
Updating/overwriting playlist in Android does not work as expected

### ISSUE THREAD

**Issue by JonteP** [vitamin-caig/zxtune#2231]
I often want to add new tracks to a playlist I created previously and resave that playlist. 
I do that in android by pressing the save button, typing the name of the current playlist and pressing overwrite.

Expected behavior: 
The playlist file "name.xspf" is overwritten.

Actual behavior: 
A new file is created: "name.xspf (1)" which ZXTune does not detect.

Workaround:
Delete the old playlist and create a new one with updated content.

**Comment by vitamin-caig** [comment]
Fixed in 9b04d441eceefc24
