### ISSUE TITLE
Bitbucket? Jira? Github? Githubissues?

### ISSUE THREAD

**Issue by grinapo** [vitamin-caig/zxtune#526]
"Official homepage" doesn't exist. Two parallel issue trackers. 
Which one is real? Which is preferred? Where's the development, and where should I enter bugs'n stuff?

**Comment by vitamin-caig** [comment]
> "Official homepage" doesn't exist. Two parallel issue trackers.
> Which one is real? Which is preferred? Where's the development, and where should I enter bugs'n stuff?

1) Open https://github.com/vitamin-caig/zxtune (main page of this repo)
2) Read carefully title ('Mirror of http://bitbucket.org/zxtune/zxtune repository https://zxtune.bitbucket.io')
...
4) PROFIT!

**Comment by grinapo** [comment]
I have (which is kind of logical since I have specifically asked about "bitbucket" in the title :-P). And I've been also read through the bitbucket page:

>ZXTune
> ZXTune is open-source crossplatform chiptunes player.
> Official page is http://zxtune.bitbucket.org

which doesn't exist. You're correct that I only have checked this, and http://bitbucket.org/zxtune/zxtune, and the github readme, and a few searches, and forgot to check bitbucket.**io**, which is yet another page. :-)

My main question is where the issues should have gone. Here's some 400+ issues, there's some ~90, but over there the issues seem not to possess any visible activity, and I started worrying whether I'm at the proper place.

**Comment by vitamin-caig** [comment]
So, you've created another issue in right place and I agree with it:) There're two more mentions of old homepage.

**Comment by vitamin-caig** [comment]
This mirror is used for automatic bugs reporting, so it's better to use bitbucket for human ones.

**Comment by grinapo** [comment]
Would you be so sweet as to include this information as well on the top of the local readme, please? :-)

**Comment by vitamin-caig** [comment]
Is it ok now?:)
