### ISSUE TITLE
Неточность в парсинге PSG формата.

### ISSUE THREAD

**Issue by Vadimatorik** [vitamin-caig/zxtune#643]
Файл: zxtune/src/formats/chiptune/aym/psg.cpp
Строка 67.
Метод: bool FastCheck(const Binary::Container& rawData);
Внутри осуществляется проверка, что файл в длину как минимум 16 байт (то есть, в размер header). В случае, если это так, то копируется полная структура (16 байт) psg файла. 
Это неверно (хотя в 99.9% работает). Вот что сказано в описании формата у Бульбы:

<<Немного дополнительной информации. Как удалось узнать, некоторые эмуляторы
сохраняют более простой заголовок - только первые четыре байта, то есть вывод
на AY начинает сохраняться уже со смещения +4.>>

**Comment by vitamin-caig** [comment]
Непонятно, куда копируется эта полная структура.
Парсится все правильно - костыль для кривых эмуляторов имеется.
Чтоб задать хоть какое-то адекватное звучание надо записать больше, чем 12 байт, включая служебную информацию.

P.S. Не надо заводить тикеты в этом репозитории - багтрекер только для робота, об этом сказано в заголовке.

**Comment by Vadimatorik** [comment]
В README.md ничего нет. Куда писать?
